from flask import Flask
from flask_sqlalchemy import SQLAlchemy, orm
# 导入配置文件
from config import config
import os
from app.models import ExchangeRateQuotation, Fund, FundNetValue, Category, SubCategory

db = SQLAlchemy()
app = Flask(__name__)

app.config.from_object(config[os.getenv('FLASK_CONFIG') or 'default'])
db.init_app(app)
app.app_context().push()

# print(c)
c1 = db.session.query(Category).filter(Category.name == 'FOF')
c1.update({Category.priority:5})
# c1 = Category(name='FOF', priority=5)
c2 = db.session.query(Category).filter(Category.name == 'QDII')
c2.update({Category.priority:3})
# c2 = Category(name='QDII', priority=3)
c3 = db.session.query(Category).filter(Category.name == '保本型')
c3.update({Category.priority:2})
# c3 = Category(name='保本型', priority=2)
c4 = db.session.query(Category).filter(Category.name == '债券型')
c4.update({Category.priority:7})
# c4 = Category(name='债券型', priority=7)
c5 = db.session.query(Category).filter(Category.name == '商品型')
c5 .update({Category.priority:1})
# c5 = Category(name='商品型', priority=1)
c6 = db.session.query(Category).filter(Category.name == '混合型')
c6 .update({Category.priority:6})
# c6 = Category(name='混合型', priority=6)
c7 = db.session.query(Category).filter(Category.name == '股票型')
c7.update({Category.priority:8})
# c7 = Category(name='股票型', priority=8)
c8 = db.session.query(Category).filter(Category.name == '货币市场型')
c8.update({Category.priority:4})
# c8 = Category(name='货币市场型', priority=4)

s1 = db.session.query(SubCategory).filter(db.and_(SubCategory.name=='FOF',SubCategory.categoryId == c1.one().id))
s1.update({SubCategory.priority:1})
# s1 = SubCategory(name='FOF', category=c1, priority=1)

s2 = db.session.query(SubCategory).filter(db.and_(SubCategory.name=='QDII股票',SubCategory.categoryId == c2.one().id))
s2.update({SubCategory.priority:4})
# s2 = SubCategory(name='QDII股票', category=c2, priority=4)
s3 = db.session.query(SubCategory).filter(db.and_(SubCategory.name=='QDII债券',SubCategory.categoryId == c2.one().id))
s3.update({SubCategory.priority:3})
# s3 = SubCategory(name='QDII债券', category=c2, priority=3)
s4 = db.session.query(SubCategory).filter(db.and_(SubCategory.name=='QDII其他',SubCategory.categoryId == c2.one().id))
s4.update({SubCategory.priority:1})
# s4 = SubCategory(name='QDII其他', category=c2, priority=1)
s5 = db.session.query(SubCategory).filter(db.and_(SubCategory.name=='QDII混合',SubCategory.categoryId == c2.one().id))
s5.update({SubCategory.priority:2})
# s5 = SubCategory(name='QDII混合', category=c2, priority=2)

s6 =db.session.query(SubCategory).filter(db.and_(SubCategory.name=='保本型',SubCategory.categoryId == c3.one().id))
s6.update({SubCategory.priority:1})
# s6 = SubCategory(name='保本型', category=c3, priority=1)

s7 = db.session.query(SubCategory).filter(db.and_(SubCategory.name=='可转换债',SubCategory.categoryId == c4.one().id))
s7.update({SubCategory.priority:6})
# s7 = SubCategory(name='可转换债', category=c4, priority=6)
s8 = db.session.query(SubCategory).filter(db.and_(SubCategory.name=='可投转债',SubCategory.categoryId == c4.one().id))
s8.update({SubCategory.priority:5})
# s8 = SubCategory(name='可投转债', category=c4, priority=5)
s10 = db.session.query(SubCategory).filter(db.and_(SubCategory.name=='二级债基',SubCategory.categoryId == c4.one().id))
s10.update({SubCategory.priority:7})
# s10 = SubCategory(name='二级债基', category=c4, priority=7)
s11 = db.session.query(SubCategory).filter(db.and_(SubCategory.name=='纯债',SubCategory.categoryId == c4.one().id))
s11.update({SubCategory.priority:9})
# s11 = SubCategory(name='纯债', category=c4, priority=9)
s12 = db.session.query(SubCategory).filter(db.and_(SubCategory.name=='债券型指数基金',SubCategory.categoryId == c4.one().id))
s12.update({SubCategory.priority:3})
# s12 = SubCategory(name='债券型指数基金', category=c4, priority=3)
s13 = db.session.query(SubCategory).filter(db.and_(SubCategory.name=='短期理财',SubCategory.categoryId == c4.one().id))
s13.update({SubCategory.priority:4})
# s13 = SubCategory(name='短期理财', category=c4, priority=4)
s14 = db.session.query(SubCategory).filter(db.and_(SubCategory.name=='一级债基',SubCategory.categoryId == c4.one().id))
s14.update({SubCategory.priority:8})
# s14 = SubCategory(name='一级债基', category=c4, priority=8)
s15 = db.session.query(SubCategory).filter(db.and_(SubCategory.name=='债券型分级基金',SubCategory.categoryId == c4.one().id))
s15.update({SubCategory.priority:2})
# s15 = SubCategory(name='债券型分级基金', category=c4, priority=2)
s16 = db.session.query(SubCategory).filter(db.and_(SubCategory.name=='债券型封闭基金',SubCategory.categoryId == c4.one().id))
s16.update({SubCategory.priority:1})
# s16 = SubCategory(name='债券型封闭基金', category=c4, priority=1)

s17 = db.session.query(SubCategory).filter(db.and_(SubCategory.name=='商品型',SubCategory.categoryId == c5.one().id))
s17.update({SubCategory.priority:1})
# s17 = SubCategory(name='商品型', category=c5, priority=1)

s18 = db.session.query(SubCategory).filter(db.and_(SubCategory.name=='偏股型',SubCategory.categoryId == c6.one().id))
s18.update({SubCategory.priority:7})
# s18 = SubCategory(name='偏股型', category=c6, priority=7)
s19 = db.session.query(SubCategory).filter(db.and_(SubCategory.name=='灵活配置型',SubCategory.categoryId == c6.one().id))
s19.update({SubCategory.priority:5})
# s19 = SubCategory(name='灵活配置型', category=c6, priority=5)
s20 = db.session.query(SubCategory).filter(db.and_(SubCategory.name=='行业偏股型',SubCategory.categoryId == c6.one().id))
s20.update({SubCategory.priority:3})
# s20 = SubCategory(name='行业偏股型', category=c6, priority=3)
s21 = db.session.query(SubCategory).filter(db.and_(SubCategory.name=='其他混合型',SubCategory.categoryId == c6.one().id))
s21.update({SubCategory.priority:1})
# s21 = SubCategory(name='其他混合型', category=c6, priority=1)
s22 = db.session.query(SubCategory).filter(db.and_(SubCategory.name=='偏债型',SubCategory.categoryId == c6.one().id))
s22.update({SubCategory.priority:6})
# s22 = SubCategory(name='偏债型', category=c6, priority=6)
s23 = db.session.query(SubCategory).filter(db.and_(SubCategory.name=='绝对收益',SubCategory.categoryId == c6.one().id))
s23.update({SubCategory.priority:2})
# s23 = SubCategory(name='绝对收益', category=c6, priority=2)
s24 = db.session.query(SubCategory).filter(db.and_(SubCategory.name=='股债平衡型',SubCategory.categoryId == c6.one().id))
s24.update({SubCategory.priority:4})
# s24 = SubCategory(name='股债平衡型', category=c6, priority=4)
s25 = db.session.query(SubCategory).filter(db.and_(SubCategory.name=='沪港深',SubCategory.categoryId == c6.one().id))
s25.update({SubCategory.priority:0})
# s25 = SubCategory(name='沪港深', category=c6, priority=0)

s26 = db.session.query(SubCategory).filter(db.and_(SubCategory.name=='股票型指数基金',SubCategory.categoryId == c7.one().id))
s26.update({SubCategory.priority:4})
# s26 = SubCategory(name='股票型指数基金', category=c7, priority=4)
s27 = db.session.query(SubCategory).filter(db.and_(SubCategory.name=='股票型主动管理',SubCategory.categoryId == c7.one().id))
s27.update({SubCategory.priority:5})
# s27 = SubCategory(name='股票型主动管理', category=c7, priority=5)
s28 = db.session.query(SubCategory).filter(db.and_(SubCategory.name=='股票型行业基金',SubCategory.categoryId == c7.one().id))
s28.update({SubCategory.priority:3})
# s28 = SubCategory(name='股票型行业基金', category=c7, priority=3)
s29 = db.session.query(SubCategory).filter(db.and_(SubCategory.name=='沪港深',SubCategory.categoryId == c7.one().id))
s29.update({SubCategory.priority:0})
# s29 = SubCategory(name='沪港深', category=c7, priority=0)
s30 = db.session.query(SubCategory).filter(db.and_(SubCategory.name=='股票型分级基金',SubCategory.categoryId == c7.one().id))
s30.update({SubCategory.priority:2})
# s30 = SubCategory(name='股票型分级基金', category=c7, priority=2)
s31 = db.session.query(SubCategory).filter(db.and_(SubCategory.name=='股票型封闭基金',SubCategory.categoryId == c7.one().id))
s31.update({SubCategory.priority:1})

# s31 = SubCategory(name='股票型封闭基金', category=c7, priority=1)

s32 = db.session.query(SubCategory).filter(db.and_(SubCategory.name=='货币市场型',SubCategory.categoryId == c8.one().id))
s32.update({SubCategory.priority:1})
# s32 = SubCategory(name='货币市场型', category=c8, priority=1)

# db.session.add_all([s1, s2, s3, s4, s5, s6, s7, s8, s10, s11, s12, s13, s14, s15, s16, s17, s18, s19, s20, s21, s22,
#                     s23, s24, s25, s26, s27, s28, s29, s30, s31, s32])
db.session.commit()
db.session.close()

print('ok')
