"""empty message

Revision ID: 20a9fb2cdbca
Revises: a7da18eaf910
Create Date: 2018-10-22 11:04:22.036287

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '20a9fb2cdbca'
down_revision = 'a7da18eaf910'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fundsnetvalue',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('annualizedRate', sa.DECIMAL(precision=22, scale=18), nullable=True),
    sa.Column('unitNav', sa.DECIMAL(precision=14, scale=10), nullable=True),
    sa.Column('navDate', sa.DateTime(), nullable=True),
    sa.Column('createTime', sa.DateTime(), nullable=True),
    sa.Column('fundId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fundId'], ['funds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_createTime', 'fundsnetvalue', ['createTime'], unique=False)
    op.create_index('ix_id_navDate', 'fundsnetvalue', ['id', 'navDate'], unique=False)
    op.create_index('ix_navDate', 'fundsnetvalue', ['navDate'], unique=False)
    op.add_column('funds', sa.Column('createTime', sa.DateTime(), nullable=True))
    op.create_index('ix_createTime', 'funds', ['createTime'], unique=False)
    op.create_index('ix_id_code_createTime', 'funds', ['id', 'code', 'createTime'], unique=False)
    op.create_index('ix_mechanismCode', 'funds', ['mechanismCode'], unique=False)
    op.drop_index('ix_acquisitionTime', table_name='funds')
    op.drop_index('ix_id_code_acquisitionTime', table_name='funds')
    op.drop_column('funds', 'acquisitionTime')
    op.drop_column('funds', 'navDate')
    op.drop_column('funds', 'annualizedRate')
    op.drop_column('funds', 'unitNav')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('funds', sa.Column('unitNav', mysql.DECIMAL(precision=14, scale=10), nullable=True))
    op.add_column('funds', sa.Column('annualizedRate', mysql.DECIMAL(precision=22, scale=18), nullable=True))
    op.add_column('funds', sa.Column('navDate', mysql.DATETIME(), nullable=True))
    op.add_column('funds', sa.Column('acquisitionTime', mysql.DATETIME(), nullable=True))
    op.create_index('ix_id_code_acquisitionTime', 'funds', ['id', 'code', 'acquisitionTime'], unique=False)
    op.create_index('ix_acquisitionTime', 'funds', ['acquisitionTime'], unique=False)
    op.drop_index('ix_mechanismCode', table_name='funds')
    op.drop_index('ix_id_code_createTime', table_name='funds')
    op.drop_index('ix_createTime', table_name='funds')
    op.drop_column('funds', 'createTime')
    op.drop_index('ix_navDate', table_name='fundsnetvalue')
    op.drop_index('ix_id_navDate', table_name='fundsnetvalue')
    op.drop_index('ix_createTime', table_name='fundsnetvalue')
    op.drop_table('fundsnetvalue')
    # ### end Alembic commands ###
