"""empty message

Revision ID: 2cd97d931c76
Revises: 20a9fb2cdbca
Create Date: 2018-10-23 00:22:50.418630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cd97d931c76'
down_revision = '20a9fb2cdbca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_category', 'funds', ['category'], unique=False)
    op.create_index('ix_id_code_title_mechanismCode', 'funds', ['id', 'code', 'title', 'mechanismCode'], unique=False)
    op.create_index('ix_subCategory', 'funds', ['subCategory'], unique=False)
    op.create_index('ix_title', 'funds', ['title'], unique=False)
    op.drop_index('ix_createTime', table_name='funds')
    op.drop_index('ix_id_code_createTime', table_name='funds')
    op.drop_index('ix_createTime', table_name='fundsnetvalue')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_createTime', 'fundsnetvalue', ['createTime'], unique=False)
    op.create_index('ix_id_code_createTime', 'funds', ['id', 'code', 'createTime'], unique=False)
    op.create_index('ix_createTime', 'funds', ['createTime'], unique=False)
    op.drop_index('ix_title', table_name='funds')
    op.drop_index('ix_subCategory', table_name='funds')
    op.drop_index('ix_id_code_title_mechanismCode', table_name='funds')
    op.drop_index('ix_category', table_name='funds')
    # ### end Alembic commands ###
