"""empty message

Revision ID: 2cf5a6b641ff
Revises: 
Create Date: 2018-10-15 14:59:52.149612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cf5a6b641ff'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchangeratequotation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('currency', sa.String(length=20), nullable=True),
    sa.Column('spotPurchasePrice', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('cashPurchasePrice', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('spotSellingPrice', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('cashSellingPrice', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('issuingTime', sa.DateTime(), nullable=True),
    sa.Column('acquisitionTime', sa.DateTime(), nullable=True),
    sa.Column('mechanismCode', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exchangeratequotation')
    # ### end Alembic commands ###
