"""Initial migration-2018-10-18

Revision ID: 49be33875814
Revises: 
Create Date: 2018-10-18 14:28:22.717345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49be33875814'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchangeratequotation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('currency', sa.String(length=20), nullable=True),
    sa.Column('spotPurchasePrice', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('cashPurchasePrice', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('spotSellingPrice', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('cashSellingPrice', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('issuingTime', sa.DateTime(), nullable=True),
    sa.Column('acquisitionTime', sa.DateTime(), nullable=True),
    sa.Column('mechanismCode', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('funds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('annualizedRate', sa.DECIMAL(precision=22, scale=18), nullable=True),
    sa.Column('unitNav', sa.DECIMAL(precision=14, scale=10), nullable=True),
    sa.Column('navDate', sa.DateTime(), nullable=True),
    sa.Column('subCategory', sa.String(length=20), nullable=True),
    sa.Column('acquisitionTime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('funds')
    op.drop_table('exchangeratequotation')
    # ### end Alembic commands ###
