"""empty message

Revision ID: 703b5a489257
Revises: 8fb896062aef
Create Date: 2018-10-18 18:36:49.069358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '703b5a489257'
down_revision = '8fb896062aef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_acquisitionTime', 'funds', ['acquisitionTime'], unique=False)
    op.create_index('ix_code', 'funds', ['code'], unique=False)
    op.create_index('ix_id_code_acquisitionTime', 'funds', ['id', 'code', 'acquisitionTime'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_id_code_acquisitionTime', table_name='funds')
    op.drop_index('ix_code', table_name='funds')
    op.drop_index('ix_acquisitionTime', table_name='funds')
    # ### end Alembic commands ###
