"""funds-add-mechanismCode-2018-10-18

Revision ID: 8fb896062aef
Revises: c94cc05386e3
Create Date: 2018-10-18 14:53:03.292940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fb896062aef'
down_revision = 'c94cc05386e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('funds', sa.Column('mechanismCode', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('funds', 'mechanismCode')
    # ### end Alembic commands ###
