"""empty message

Revision ID: a7da18eaf910
Revises: 703b5a489257
Create Date: 2018-10-19 15:53:47.429028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7da18eaf910'
down_revision = '703b5a489257'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_acquisitionTime', 'exchangeratequotation', ['acquisitionTime'], unique=False)
    op.create_index('ix_issuingTime', 'exchangeratequotation', ['issuingTime'], unique=False)
    op.create_index('ix_mechanismCode', 'exchangeratequotation', ['mechanismCode'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_mechanismCode', table_name='exchangeratequotation')
    op.drop_index('ix_issuingTime', table_name='exchangeratequotation')
    op.drop_index('ix_acquisitionTime', table_name='exchangeratequotation')
    # ### end Alembic commands ###
