"""update-funds-pro-2018-10-18

Revision ID: c94cc05386e3
Revises: e19cb2565d43
Create Date: 2018-10-18 14:42:56.377408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c94cc05386e3'
down_revision = 'e19cb2565d43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('funds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('annualizedRate', sa.DECIMAL(precision=22, scale=18), nullable=True),
    sa.Column('unitNav', sa.DECIMAL(precision=14, scale=10), nullable=True),
    sa.Column('navDate', sa.DateTime(), nullable=True),
    sa.Column('subCategory', sa.String(length=20), nullable=True),
    sa.Column('acquisitionTime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('funds')
    # ### end Alembic commands ###
