"""Initial migration-2018-10-18

Revision ID: e7ab081688a1
Revises: adc6116b2cc2
Create Date: 2018-10-18 14:37:24.506755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7ab081688a1'
down_revision = 'adc6116b2cc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('funds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('annualizedRate', sa.DECIMAL(precision=22, scale=18), nullable=True),
    sa.Column('unitNav', sa.DECIMAL(precision=14, scale=10), nullable=True),
    sa.Column('navDate', sa.DateTime(), nullable=True),
    sa.Column('subCategory', sa.String(length=20), nullable=True),
    sa.Column('acquisitionTime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('funds')
    # ### end Alembic commands ###
